#lang racket

#|
Exercise 1.15.
The sine of an angle (specified in radians) can be computed by making use of the
approximation sin x x if x is sufficiently small, and the trigonometric identity 
|#

(require racket/trace)
(define (cube x) (* x x x))

(writeln "Method 1:")
; p(x) = -3*x + 4x^3
(define (p x)
  (- (* 3 x)
     (* 4 (cube x))))

(define (sine angle)
    (if (not (> (abs angle) 0.1))
        angle
        (p (sine (/ angle 3.0)))))

(trace sine)
(sine 30)

(writeln "Method 2 using nested procedures")

(define (sine-m2 angle)
  (define (p x) (- (* 3 x) (* 4 (cube x))))
  (define (cube x) (* x x x))
    (if (not (> (abs angle) 0.1))
        angle
        (p (sine-m2 (/ angle 3.0)))))

(sine-m2 30)
;;a. How many times is the procedure p applied when (sine 12.15) is evaluated?


;;b. What is the order of growth in space and number of steps (as a function of a) used by the process generated by the sine procedure when (sine a) is evaluated?



